version: '3.8'
services:
  nginx-local:
    image: nginx:stable
    container_name: ylai-local-nginx
    volumes:
      - ../docker/local-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../frontend/dist:/usr/share/nginx/html:ro
    network_mode: "host"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
